config/routes.rb
Rails.application.routes.draw do
  root "homes#top"

  resources :lists, only: [:new, :index, :show, :edit, :create, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def index
    @lists = List.all
  end

  def show
  end

  def edit
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

<%= link_to "新規投稿", new_list_path %>
<%= link_to "投稿一覧", lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>本文</th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "トップ画面", root_path %>

app/views/lists/new.html.erb
<h1>新規登録</h1>

<%= form_with model: @list do |f| %>
  <div><%= f.label :title, "タイトル" %></div>
  <div><%= f.text_field :title %></div>
  <div><%= f.label :body, "本文" %></div>
  <div><%= f.text_area :body %></div>
  <div><%= f.submit "新規投稿" %></div>
<% end %>